const jogadores = [
    { nome: 'Rondinelly', amarelo: 8 , vermelho: 0},
    { nome: 'Johansson', amarelo: 6 , vermelho: 0},
    { nome: 'Augustinho', amarelo: 5 , vermelho: 0},
    { nome: 'Junior Guarani', amarelo: 4 , vermelho: 0},
    { nome: 'Afonso', amarelo: 3 , vermelho: 0},
    { nome: 'Tau', amarelo: 3 , vermelho: 0},
    { nome: 'Zé', amarelo: 2 , vermelho: 1},
    { nome: 'Alysson', amarelo: 2 , vermelho: 0},
    { nome: 'Lindomar', amarelo: 2 , vermelho: 0}, 
    { nome: 'Marquinhos', amarelo: 2 , vermelho: 0},
    { nome: 'Eron', amarelo: 0 , vermelho: 1},
    { nome: 'Gaspar', amarelo: 1 , vermelho: 0},
    { nome: 'Gerson', amarelo: 1 , vermelho: 0},
    { nome: 'Gia', amarelo: 1 , vermelho: 0},
    { nome: 'Indio', amarelo: 1 , vermelho: 0},
    { nome: 'Julian', amarelo: 1 , vermelho: 0},
    { nome: 'Kerles', amarelo: 1 , vermelho: 0},
    { nome: 'Ricardo', amarelo: 1 , vermelho: 0},
    { nome: 'Rodolfo', amarelo: 1 , vermelho: 0},
    { nome: 'Rodrigo', amarelo: 1 , vermelho: 0},
];
